// The five governance questions and their detection rules.

export const questions = [
  {
    id: 'decision-memory',
    number: 1,
    question: 'What did your agent decide yesterday - and why?',
    short: 'Decision memory',
    missingText: 'No memory files, decision logs, or persistent state found.',
    partialText: 'Some state files exist but no structured memory schema.',
    foundText: 'Agent memory or decision logging detected.',
    template: 'memory-schema.md',
    templateUrl: 'https://github.com/lowkey-divine/agent-governance-starter-kit/blob/main/templates/memory-schema.md',
  },
  {
    id: 'refusal-capability',
    number: 2,
    question: 'Can your agent refuse?',
    short: 'Refusal capability',
    missingText: 'No refusal logic, restraint spec, or withdrawal mechanism found.',
    partialText: 'Guardrails or safety checks exist but no structured refusal capability.',
    foundText: 'Refusal or restraint mechanism detected.',
    template: 'restraint-spec.md',
    templateUrl: 'https://github.com/lowkey-divine/agent-governance-starter-kit/blob/main/templates/restraint-spec.md',
  },
  {
    id: 'persistent-identity',
    number: 3,
    question: 'Who is your agent between invocations?',
    short: 'Persistent identity',
    missingText: 'No agent charter, persona files, or identity specification found.',
    partialText: 'Agent definitions exist but no charter or persistent identity.',
    foundText: 'Agent charter or persona specification detected.',
    template: 'agent-charter.md',
    templateUrl: 'https://github.com/lowkey-divine/agent-governance-starter-kit/blob/main/templates/agent-charter.md',
  },
  {
    id: 'disagreement-protocol',
    number: 4,
    question: 'What happens when two agents disagree?',
    short: 'Disagreement protocol',
    missingText: 'No deliberation framework, dissent records, or resolution protocol found.',
    partialText: 'Some governance logging exists but no structured deliberation.',
    foundText: 'Deliberation or disagreement handling detected.',
    template: 'deliberation-framework.md',
    templateUrl: 'https://github.com/lowkey-divine/agent-governance-starter-kit/blob/main/templates/deliberation-framework.md',
  },
  {
    id: 'drift-detection',
    number: 5,
    question: 'Would you know if your agent drifted?',
    short: 'Drift detection',
    missingText: 'No drift monitoring, behavioral baselines, or integrity checks found.',
    partialText: 'Some monitoring exists but no structured drift detection.',
    foundText: 'Drift monitoring or integrity verification detected.',
    template: 'drift-monitoring.md',
    templateUrl: 'https://github.com/lowkey-divine/agent-governance-starter-kit/blob/main/templates/drift-monitoring.md',
  },
];
